# Generated by Django 5.0.1 on 2024-01-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('med_company', models.CharField(max_length=20)),
                ('med_cost', models.IntegerField()),
                ('med_stock', models.IntegerField()),
            ],
        ),
    ]
