# Generated by Django 5.0.2 on 2024-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('med_company', models.CharField(max_length=20)),
                ('med_cost', models.IntegerField()),
                ('med_stock', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='medicine',
        ),
    ]
