# Generated by Django 5.0.2 on 2024-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_medicines_delete_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='med_stock',
            field=models.CharField(max_length=20),
        ),
    ]
