# Generated by Django 5.0.2 on 2024-02-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_medicines_med_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicines',
        ),
    ]
