# Generated by Django 5.0.2 on 2024-02-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_medicine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
