# Generated by Django 5.0.2 on 2024-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_purchase_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cus_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='phone_no',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
