# Generated by Django 5.0.2 on 2024-03-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_purchase_cus_name_remove_purchase_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_name',
            field=models.CharField(max_length=30),
        ),
    ]
